params:
  project_name: "District 14"
  fishery_name: "Skagit winter steelhead 2021"
  est_date_start: "2021-02-01"
  est_date_end: "2021-04-15"
  est_catch_groups:
    - species: Steelhead
      life_stage: Adult
      fin_mark: UM
      fate: Released
    - species: Coho
      life_stage: Adult
      fin_mark: AD
      fate: Kept
  study_design: "Standard"  
  boat_type_collapse: "Yes"
  fish_location_determines_type: "No"
  angler_type_kayak_pontoon: "boat" 
  person_count_type: "group"
  period_pe: "week"
  period_bss: "day"
  days_wkend: !r c('Saturday', 'Sunday')
  day_length_expansion: "night closure"
  min_fishing_time: 0.5
  bss_model_file_name: "BSS_creel_model_02_2024-04-03.stan"
  model_used: ["pe"]
  data_grade: "provisional"
  export: "no"
  export_tables: "both"
